package ru.sber.tb_bot_group6.finalStateMachine

enum class StepCode(val type: StepType, val botPause: Boolean) {
    START(StepType.SIMPLE_TEXT, false),
    ADD_NAME_OF_MEETING(StepType.SIMPLE_TEXT, true),
    ADD_DESCRIPTION_OF_MEETING(StepType.SIMPLE_TEXT, true),
    ADD_POINT_OF_MEETING(StepType.SIMPLE_TEXT, true),
    ACCEPT_MEETING_BUTTON_REQUEST(StepType.INLINE_KEYBOARD_MARKUP, true),
    CHOOSE_CITY_BUTTON_REQUEST(StepType.INLINE_KEYBOARD_MARKUP, true),
    SEARCH_MEETING_BUTTON_REQUEST(StepType.INLINE_KEYBOARD_MARKUP, false),
    ORGANISE_MEETING_BUTTON_REQUEST(StepType.INLINE_KEYBOARD_MARKUP, true),
    ACCEPT_MEETING_BUTTON_RESPONSE(StepType.SIMPLE_TEXT, false),
    CHOOSE_CITY_BUTTON_RESPONSE(StepType.SIMPLE_TEXT, false),
    SEARCH_MEETING_BUTTON_RESPONSE(StepType.SIMPLE_TEXT, false),
    ORGANISE_MEETING_BUTTON_RESPONSE(StepType.SIMPLE_TEXT, false),

}

enum class StepType {
    SIMPLE_TEXT,
    INLINE_KEYBOARD_MARKUP
}